[versions]
activity = "1.9.3"
agentwebCore = "v5.1.1-androidx"
agp = "8.4.2"
appcompat = "1.6.1"
appcompatVersion = "1.0.0"
appintro = "6.3.1"
banner = "2.2.3"
baserecyclerviewadapterhelper = "3.0.14"
boommenu = "2.1.1"
constraintlayout = "2.1.4"
converterGson = "2.9.0"
coreSplashscreen = "1.0.1"
espressoCore = "3.5.1"
glide = "4.16.0"
jacksonAnnotations = "2.15.2"
jacksonDatabind = "2.15.2"
junit = "4.13.2"
junitVersion = "1.1.5"
lifecycleLivedataKtx = "2.6.1"
lifecycleViewmodelKtx = "2.6.1"
lombok = "1.18.28"
material = "1.10.0"
mpandroidchart = "v3.1.0"
navigationFragment = "2.6.0"
navigationUi = "2.6.0"
refreshLayoutKernel = "3.0.0-alpha"
refreshHeaderClassics = "3.0.0-alpha"
retrofit = "2.9.0"
legacySupportV4 = "1.0.0"

[libraries]
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
agentweb-core = { module = "io.github.justson:agentweb-core", version.ref = "agentwebCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
appcompat-v100 = { module = "androidx.appcompat:appcompat", version.ref = "appcompatVersion" }
appintro = { module = "com.github.AppIntro:AppIntro", version.ref = "appintro" }
banner = { module = "io.github.youth5201314:banner", version.ref = "banner" }
baserecyclerviewadapterhelper = { module = "io.github.cymchad:BaseRecyclerViewAdapterHelper", version.ref = "baserecyclerviewadapterhelper" }
boommenu = { module = "com.nightonke:boommenu", version.ref = "boommenu" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }
core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jacksonDatabind" }
jackson-annotations = { module = "com.fasterxml.jackson.core:jackson-annotations", version.ref = "jacksonAnnotations" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
mpandroidchart = { module = "com.github.PhilJay:MPAndroidChart", version.ref = "mpandroidchart" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigationFragment" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigationUi" }
refresh-footer-classics = { module = "io.github.scwang90:refresh-footer-classics", version.ref = "refreshLayoutKernel" }
refresh-header-classics = { module = "io.github.scwang90:refresh-header-classics", version.ref = "refreshHeaderClassics" }
refresh-layout-kernel = { module = "io.github.scwang90:refresh-layout-kernel", version.ref = "refreshLayoutKernel" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
legacy-support-v4 = { group = "androidx.legacy", name = "legacy-support-v4", version.ref = "legacySupportV4" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }